name: bratur
description: Get your business trips organized today!

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  redux: ^4.0.0
  redux_logging: ^0.4.0
  redux_thunk: ^0.3.0
  redux_epics: ^0.13.0
  flutter_redux: ^0.6.0
  freezed_annotation: ^0.7.1
  flutter_map: ^0.8.2
  user_location:
    git:
      url: https://github.com/joharei/user_location_plugin.git
      ref: 39/bugfix-location-marker-disappears
  flutter_map_marker_cluster: ^0.2.7
  geolocation: ^1.1.2
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.0
  flutter_svg: ^0.17.3+1
  intl: ^0.16.1
  google_fonts: ^0.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.1
  freezed: ^0.10.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/Rocket-Digital-black.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Arial
      fonts:
        - asset: fonts/Arial.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
