name: Build and deploy Web app
on:
  push:
    paths:
      - 'web_app/**'
      - '.github/workflows/web.yml'

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/web_app/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cd web_app
          yarn install
          yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    name: Deploy

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build
          path: build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
